"use strict";

const catbook = {
  newsfeed: [],
  friends: {},
  friendNames: ["tamaroh"],
};

catbook.friendNames.forEach((name) => {
  catbook.friends[name] = [];
});

const getRandomElement = (array) => {
  const randomIndex = Math.floor(Math.random() * array.length);
  return array[randomIndex];
};

const starters = [
  "totally just",
  "just",
  "completely",
  "waaaaah! I",
  "I just",
  "a salaryman",
  "a salaryman",
  "yesterday I",
  "a ninja",
  "my boss",
  "early this morning I",
  "unexpectedly",
  "in the middle of nowhere, I",
  "while eating breakfast, I",
  "can you believe it? I",
  "at the supermarket, I",
  "running late, I",
  "during my lunch break, I",
  "without any warning, I",
  "while browsing the internet, I",
  "amazingly, I",
  "at the gym, I",
  "in the pouring rain, I",
  "while on a rollercoaster, I",
  "during a job interview, I",
  "while sleepwalking, I",
  "in a parallel universe, I",
  "during a power outage, I",
  "during a thunderstorm, I",
  "while skydiving, I",
  "in the middle of a crowd, I",
  "during a zombie apocalypse, I",
  "while doing yoga, I",
  "in a dream, I",
  "while riding a unicorn, I",
  "at a haunted house, I",
  "during a magic show, I",
  "while learning to juggle, I",
  "in a hot air balloon, I",
  "during a dance competition, I",
  "while swimming with dolphins, I",
  "in a time machine, I",
  "during a chess tournament, I",
  "while bungee jumping, I",
  "at a fancy restaurant, I",
  "during a marathon, I",
  "while climbing Mount Everest, I",
  "in the middle of a movie, I",
  "during a space mission, I",
  "while volunteering at an animal shelter, I",
  "at a rock concert, I",
  "during a cooking class, I",
];
const verbs = [
  "ate",
  "drank",
  "threw up in",
  "refactored",
  "iterated on",
  "thought about",
  "threw up on",
  "saw",
  "walked to",
  "got lost in",
  "walked into",
  "googled",
  "drove",
  "ran to",
  "worked on",
  "slept on",
  "slept in",
  "discovered",
  "invented",
  "fixed",
  "danced with",
  "conquered",
  "chased",
  "built",
  "wrote",
  "laughed at",
  "sang to",
  "painted",
  "sculpted",
  "learned from",
  "exercised with",
  "played",
  "argued with",
  "cooked",
  "explored",
  "captured",
  "studied",
  "questioned",
  "navigated",
  "solved",
  "saved",
  "defeated",
  "assembled",
  "designed",
  "measured",
  "inspected",
  "programmed",
  "calculated",
  "analyzed",
  "collaborated with",
  "experimented on",
];
const fillers = [
  "my",
  "your",
  "his",
  "her",
  "my favorite",
  "a beautiful",
  "a delicious",
  "that",
  "this",
  "an interesting",
  "",
  "the best",
  "the greatest",
  "a delightful",
  "an extraordinary",
  "a mesmerizing",
  "an enchanting",
  "a breathtaking",
  "a captivating",
  "a remarkable",
  "an incredible",
  "a stunning",
  "an amazing",
  "a fantastic",
  "a fabulous",
  "a marvelous",
  "an awe-inspiring",
  "an impressive",
  "an outstanding",
  "a phenomenal",
  "a memorable",
  "a magical",
  "a thrilling",
  "a sensational",
  "a spectacular",
  "an epic",
  "a mind-blowing",
  "a phenomenal",
  "an extraordinary",
  "a jaw-dropping",
  "a magnificent",
  "an astonishing",
  "an exceptional",
  "a wondrous",
  "a radiant",
  "a delightful",
  "a joyous",
  "an exhilarating",
  "a blissful",
  "a radiant",
];
const nouns = [
  "restaurant",
  "omakase",
  "hitomedia",
  "family mart",
  "private jet",
  "mama",
  "lawsons",
  "conbini",
  "whisky",
  "onigiri",
  "car",
  "food",
  "house",
  "toilet",
  "Tokyo",
  "city",
  "iPhone",
  "Google",
  "unicorn",
  "mess",
  "pirate ship",
  "ninja",
  "beach",
  "mountain",
  "ocean",
  "jungle",
  "forest",
  "garden",
  "castle",
  "book",
  "movie",
  "song",
  "painting",
  "adventure",
  "dream",
  "journey",
  "puzzle",
  "treasure",
  "magazine",
  "gadget",
  "camera",
  "game",
  "sunset",
  "sunrise",
  "star",
  "moon",
  "sky",
  "rainbow",
  "wind",
  "fire",
  "island",
];
const hashtags = [
  "#techlife",
  "#tokyo",
  "#japan",
  "#interesting",
  "#til",
  "#lol",
  "#tgifriday",
  "#hashtags",
  "#japanlife",
  "#oops",
  "",
  "#adventure",
  "#inspiration",
  "#travelgram",
  "#foodie",
  "#naturelovers",
  "#photography",
  "#art",
  "#fitness",
  "#music",
  "#fashion",
  "#love",
  "#instagood",
  "#explore",
  "#beautiful",
  "#wanderlust",
  "#instadaily",
  "#selfie",
  "#happy",
  "#motivation",
  "#instalove",
  "#photooftheday",
  "#smile",
  "#instapic",
  "#follow",
  "#instamood",
  "#style",
  "#instafashion",
  "#fun",
  "#life",
  "#summer",
  "#friends",
  "#likeforlike",
  "#instatravel",
  "#travel",
  "#sunset",
  "#beauty",
  "#foodporn",
  "#goodvibes",
  "#quoteoftheday",
  "#throwback",
  "#instaquote",
];
const feelings = [
  "😄",
  "😏",
  "😅",
  "😨",
  "😫",
  "😢",
  "😡",
  "😴",
  "😎",
  "😊",
  "😃",
  "😒",
  "😂",
  "😱",
  "😩",
  "😭",
  "🤬",
  "😪",
  "🕶️",
  "🙂",
  "🤩",
  "😉",
  "😋",
  "😳",
  "😓",
  "🥱",
  "😇",
  "😅",
  "🤔",
  "😀",
  "🙄",
  "🤣",
  "😰",
  "😔",
  "😂",
  "🙃",
  "🥳",
  "😌",
  "😬",
  "😎",
  "😁",
  "😑",
  "😆",
  "😲",
  "😥",
  "🤯",
  "🙏",
  "😍",
  "🤗",
  "😞",
  "😉",
  "😅",
  "😪",
];
const images = [];

const usedImageUrls = new Set();

const getImageUrl = () => {
  const baseUrl =
    Math.random() < 0.5
      ? "https://cataas.com/cat"
      : "https://cataas.com/cat/gif";
  return `${baseUrl}?${Math.random()}`;
};

const generateRandomText = () => {
  return [
    getRandomElement(starters),
    getRandomElement(verbs),
    getRandomElement(fillers),
    getRandomElement(nouns),
    getRandomElement(hashtags),
  ].join(" ");
};

const generatePostObj = (timeOffset) => {
  const timestamp = timeOffset
    ? new Date(new Date().getTime() - timeOffset)
    : new Date();

  return {
    friend: getRandomElement(catbook.friendNames),
    text: generateRandomText(),
    feeling: getRandomElement(feelings),
    image: getRandomElement(images),
    timestamp,
  };
};

const addPost = (obj) => {
  const friend = obj.friend;
  catbook.friends[friend].push(obj);
  catbook.newsfeed.push(obj);
};

const createPost = (timeOffset) => {
  const newPost = generatePostObj(timeOffset);
  addPost(newPost);
};

for (let i = 1; i < 10; i++) {
  const timeOffset = (2 * (10 - i) + Math.random()) * 60 * 60 * 1000;
  createPost(timeOffset);
}

const scheduler = () => {
  createPost(null);
  const setTime = Math.random() * 5 * 1000;
  setTimeout(scheduler, setTime);
};

scheduler();
